school:
  enabled: true
  klass-list:
    -
      student-list:
        -
          id: 100
          name: ACLASS-100
        -
          id: 101
          name: ACLASS-101
    -
      student-list:
        -
          id: 200
          name: BCLASS-200
        -
          id: 201
          name: BCLASS-201

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      maximum-pool-size: 10
      minimum-idle: 2
