school:
  enabled: true
  klass-list:
    -
      student-list:
        -
          id: 100
          name: ACLASS-100
        -
          id: 101
          name: ACLASS-101
    -
      student-list:
        -
          id: 200
          name: BCLASS-200
        -
          id: 201
          name: BCLASS-201

